[package]
name = "myapp"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ascii_table = "4.0.3"
base64 = "0.22.1"
cli-table = "0.4.9"
iced = "0.12.1"
serial_enumerator = "0.2.12"
